-- SQL Seed Data for Chapters & Ambassadors (148 Chapters from CSV)

INSERT INTO chapters (name, city, lead_name, whatsapp_link, members_count, badge) VALUES
('GIK Institute of Technology', 'Swabi / Topi', 'Campus Team', 'https://chat.whatsapp.com/Bu6sGlCKukAJ65561Vsuil?s=cl&p=a&mlu=4&ilr=4', 39, 'Official'),
('Government Postgraduate college Haripur Chapter', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/L1V0ACm1dNH8EonzVSmiqs?s=cl&p=a&mlu=4&ilr=4', 46, 'Growing'),
('University of Sargodha – Sargodha', 'Sargodha', 'Campus Team', 'https://chat.whatsapp.com/HjoEGCKSRGp9IEF949Op6b?s=cl&p=a&mlu=4&ilr=4', 53, 'Official'),
('Benazir Bhutto Shaheed University Lyari Karachi.', 'Karachi', 'Campus Team', 'https://chat.whatsapp.com/Bs8cCSfhHWQ7Zx0Es5TmRG?s=cl&p=a&mlu=4&ilr=4', 60, 'Top Active'),
('Iqra University', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/Gi1rBlRXGtN0d4UEHxaZo2?s=cl&p=a&ilr=1', 67, 'Official'),
('IMNSU Multan', 'Multan', 'Campus Team', 'https://chat.whatsapp.com/BSIYjbS2JsUBjOZClVOIL3?s=cl&p=a&ilr=1', 74, 'Growing'),
('FJWU Chapter 5', 'Rawalpindi', 'Campus Team', 'https://chat.whatsapp.com/C3ukrgKUKt9BJjqZTFN22W?s=cl&p=a&ilr=1', 81, 'Official'),
('NED Chapter-6', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/G07KRu0Wo8EBhtyku84SEb?s=cl&p=a&ilr=1', 88, 'Growing'),
('Dha Suffa Chapter', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/JzZA2SRH8mk7JYWcDbhp3G?s=cl&p=a&ilr=1', 95, 'Top Active'),
('(PAF-IAST) Chapter', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/KgKAxi8gSkAHt3VW5Cc2lA?s=cl&p=a&ilr=1', 102, 'Growing'),
('(Dawood University ) Chapter', 'Pakistan', 'syed wasif', 'https://chat.whatsapp.com/HtVfPxaatE9CqbdcTPEwHA?s=cl&p=a&ilr=1', 29, 'Official'),
('GIK Institute of Technology', 'Swabi / Topi', 'Campus Team', 'https://chat.whatsapp.com/Bu6sGlCKukAJ65561Vsuil?s=cl&p=a&ilr=1', 36, 'Growing'),
('NUML Chap', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/CgCn9cRSERV4eCQnouZZI9?s=cl&p=a&ilr=1', 43, 'Official'),
('FJWU Chapter 1', 'Rawalpindi', 'Khadija Malik', 'https://chat.whatsapp.com/HpnWQAaN55qH0y6wy8haaP?s=cl&p=a&ilr=1', 50, 'Top Active'),
('IBA University PUNJAB', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/E84rXhC33W7GBx977zTPFV?s=cl&p=a&ilr=1', 57, 'Official'),
('Dow University of Health Sciences', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/KANdeUIVyM22zViEvacNPE?s=cl&p=a&ilr=1', 64, 'Growing'),
('IBA Sukkur Chapter 02', 'Sukkur', 'Hafsa Noor', 'https://chat.whatsapp.com/DH4RDN3IQtE2qoBGlVdP52?s=cl&p=a&ilr=1', 71, 'Official'),
('Abdul Wali khan university Mardan Chap', 'KPK / Mardan', 'Campus Team', 'https://chat.whatsapp.com/DJHmgZSmWPC7ckA3xTjZtL?s=cl&p=a&ilr=1', 78, 'Growing'),
('Virtual University', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/CYxt1ghSDYgCRD1DlmVz3Y?s=cl&p=a&ilr=1', 85, 'Top Active'),
('Begum Nusrat Bhutto women university sukkur', 'Sukkur', 'Campus Team', 'https://chat.whatsapp.com/H2hEwDApiZdAPppTRLOQ9O?s=cl&p=a&ilr=1', 92, 'Growing'),
('Comsats University Chapter 04', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/BwiCmDjwYPyJ82LYV3NVid?s=cl&p=a&ilr=1', 99, 'Official'),
('FJWU Chapter 6', 'Rawalpindi', 'Campus Team', 'https://chat.whatsapp.com/LZ8YV2mz6pADWBlKBMvVYU', 26, 'Growing'),
('Federal Urdu University', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/JyZaqyUyq7ZD5nFOVNJFgX', 33, 'Official'),
('AROR University', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/C4lJChCQIyS3zNzeo3p1z6', 40, 'Top Active'),
('PMAS Arid Agriculture University', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/Fig5yTWHWZxKE6qFa1UR8e', 47, 'Official'),
('SZABIST Karachi Chapter 01', 'Karachi', 'Sanjana Lokwani', 'https://chat.whatsapp.com/DvxpHjpAPYr4eOE8tYgH24', 54, 'Growing'),
('NED Chapter 04', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/HVyFv9DPTbZ8UUCxs86raf', 61, 'Official'),
('SZABIST Karachi Chapter 02', 'Karachi', 'Campus Team', 'https://chat.whatsapp.com/KorUBH91ZK880Ha0Y1hjsI', 68, 'Growing'),
('Mehran University Chapter', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/DU23DAwBBctIMiBb8hd7SH', 75, 'Top Active'),
('IBA DADU Chapter', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/CWEEnRzXqLILK8L2gQoVk2', 82, 'Growing'),
('IBA Sukkur Chapter 01', 'Sukkur', 'Campus Team', 'https://chat.whatsapp.com/F5UYhbjFqIJ2AhWuqSXfn2', 89, 'Official'),
('FJWU Chapter 4', 'Rawalpindi', 'Aiman Iqbal', 'https://chat.whatsapp.com/B7s3XGlA59VIXQs0h2Fo1G', 96, 'Growing'),
('FJWU Chapter 2', 'Rawalpindi', 'Campus Team', 'https://chat.whatsapp.com/FHrZFkFYNm1ESbZhRyTuOO', 103, 'Official'),
('UET Chap 1', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/DrAW7S8qp1c8cBAM4blQrM', 30, 'Top Active'),
('Career Hub', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/ETnejlUsfDcD4pHGsVoL67', 37, 'Official'),
('FAST NUCES', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/DDHTugCN27e3Lwb6t3ZYvL', 44, 'Growing'),
('University of the Punjab Chapter', 'Pakistan', 'Rabya Samman', 'https://chat.whatsapp.com/DDxduJiRLJ5EEeeCPJovrW', 51, 'Official'),
('FJWU Chapter 3', 'Rawalpindi', 'Campus Team', 'https://chat.whatsapp.com/LvWaIHpKiiuLfy61XOwrdI', 58, 'Growing'),
('SAUIT Chapter', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/GDexjELeF5c3ypway6J58k', 65, 'Top Active'),
('ChangeMakers (FAST-NUCES)', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/KpPDWS9yHPt70TlfOYhMPc', 72, 'Growing'),
('Quaid-e-Azam University', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/LquMoTGEZUC058u0J5Urdg', 79, 'Official'),
('Dawood University Chapter 02', 'Pakistan', 'Abdul Waris', 'https://chat.whatsapp.com/L8vIgXoNijG9dYVPVY1vV4', 86, 'Growing'),
('University of Mianwali Chap 2', 'Pakistan', 'Manahil Rehman', 'https://chat.whatsapp.com/CGE5pFVa8tP476YcvYhd08', 93, 'Official'),
('NED Chapter-2', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/G0Au62Z4ixDJSQUFsgdQHH', 100, 'Top Active'),
('UET Mardan| CV • LinkedIn • Jobs', 'KPK / Mardan', 'Campus Team', 'https://chat.whatsapp.com/BEXTLcrJvaE59clyo83Kjf?s=cl&p=a&mlu=4&ilr=4', 27, 'Official'),
('University of Mianwali', 'Pakistan', 'Manahil Rehman', 'https://chat.whatsapp.com/K3cZVioKnbO3I1Me0x4Nig', 34, 'Growing'),
('Namal University Chapter', 'Pakistan', 'Tanzila Younas', 'https://chat.whatsapp.com/J1tZm2n6luR2viYLf9Wg6k', 41, 'Official'),
('Air University', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/KZ8cGGFf0gr625SQZEGSqQ', 48, 'Growing'),
('COMSATS University Chapter 02', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/Ee9anrH8Z1cFA9E6wk4Fa6', 55, 'Top Active'),
('Bahria University Chapter 02', 'Pakistan', 'Taha fayyaz', 'https://chat.whatsapp.com/FoIxN00DO0w5w1oVD4UA26', 62, 'Growing'),
('Superior Chap', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/LpaJCZvTs3aHjJ7iem0pBt', 69, 'Official'),
('Government College University Hyderabad Chap', 'Sindh / Jamshoro', 'Campus Team', 'https://chat.whatsapp.com/KWyfpKxJJuLGQRhMNB0gG9', 76, 'Growing'),
('Bahria Chapter', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/Lq8rj1QUumy5kdWkDBWvoB', 83, 'Official'),
('Sindh Agriculture University Chapter', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/LiNmw4RaHvWGTRV3EJMifu', 90, 'Top Active'),
('ChangeMakers (Central Punjab University - Chapter)', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/KlgcbqAUkny7BMmUBMermK', 97, 'Official'),
('IBA Karachi Chapter', 'Karachi', 'Campus Team', 'https://chat.whatsapp.com/DeGjsIv0vzU4DxHc6Ag9mf', 104, 'Growing'),
('University of Management and Technology', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/Ib6YgdExMD7BGaEFzd6YNM', 31, 'Official'),
('University of Karachi - 3', 'Karachi', 'Campus Team', 'https://chat.whatsapp.com/JKixYlsLmbo6D6WZen9b6C', 38, 'Growing'),
('IOBM Chapter', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/Lq7ZUzMHHIKDTfiy32BIhD', 45, 'Top Active'),
('Al-Ghazali University', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/HoBC959G5352jTEilTonSq', 52, 'Growing'),
('(Government College University)', 'Pakistan', 'Tanzila Anwar', 'https://chat.whatsapp.com/DjLFMKRbfF4JmI0COfTx0T', 59, 'Official'),
('University of Karachi (Chapter-1)', 'Karachi', 'Campus Team', 'https://chat.whatsapp.com/DUNeSlJ50roADaHdUZb0Ht', 66, 'Growing'),
('Indus University', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/Lf5QQ1bWpyx61k546tIaH6', 73, 'Official'),
('Pakistan Institute of Engineering & Applied Sciences (PIEAS) - Chapter', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/BbNuRRD6pJ4BY1e4jmA4SI', 80, 'Top Active'),
('NED Chapter-1', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/JzNtT2fxMdDBrp3jRJqIPw', 87, 'Official'),
('University of Sargodha – Sargodha', 'Sargodha', 'Campus Team', 'https://chat.whatsapp.com/HjoEGCKSRGp9IEF949Op6b', 94, 'Growing'),
('Sindh Agriculture University', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/Kxkfkc2rwYD51HUX4CdCrQ', 101, 'Official'),
('SMIU', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/JDPnEjl3GGPABB0Yp3yUlK', 28, 'Growing'),
('Mehran University Chapter 2', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/KgiNU6E4RXwH8JEz7U0QfS', 35, 'Top Active'),
('MAJU Chapter', 'Pakistan', 'Agha Hassan Mavia', 'https://chat.whatsapp.com/HpxbanTFwE85fbXnQDGHTj', 42, 'Growing'),
('University of Wah Cantt', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/EyheJn7f4AN5NiSluV2UKK', 49, 'Official'),
('University of Sindh Jamshoro', 'Sindh / Jamshoro', 'Campus Team', 'https://chat.whatsapp.com/HZr2dfZzo7hG9waUEkBWIs', 56, 'Growing'),
('NED Chapter-7', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/HsuEBniMOCFB3YEmnRCX8M', 63, 'Official'),
('Govt islamia law college', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/KMYq2Bo3tjs6dcuaaff7XF', 70, 'Top Active'),
('Punjab University College of Information Technology', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/EXODcEQkkiMIi3tt4tC0Mh', 77, 'Official'),
('International Islamic University', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/DyBG5jJM2Xn6XFoy2Ax9Zu', 84, 'Growing'),
('PAF KIET', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/H9AWUn4kcFZ1oR6Cq5urtw', 91, 'Official'),
('University of Sahiwal', 'Sahiwal', 'Campus Team', 'https://chat.whatsapp.com/JBPsxrvGDaKHe0BRFFAaxr', 98, 'Growing'),
('Gomal University', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/KLQtvI0oFzRAJPcXQUwod4', 25, 'Top Active'),
('Sindh  University', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/G5GgBG8pOXvLsKdj7bnG1U', 32, 'Growing'),
('Preston University', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/LskzjH6d4o1EJiDKDGctn2', 39, 'Official'),
('Jinnah University for Women – Karachi', 'Karachi', 'Campus Team', 'https://chat.whatsapp.com/HydUZ7SPVYO1ogZ48olDtv', 46, 'Growing'),
('The Islamia University of Bahawalpur', 'Bahawalpur', 'Timsal Hassan', 'https://chat.whatsapp.com/DqKOhU0cjLQ4vZzH9QDPcc', 53, 'Official'),
('Quaid-e-Awam University', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/INpXL56gWjVDF3C64MvKPX', 60, 'Top Active'),
('Comsats University Chapter 03', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/HtuIxQrl3QXBhpu4ng7zLx', 67, 'Official'),
('NED Chapter-3', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/H7Wbn51q3zf2JLAPmRaABp', 74, 'Growing'),
('University of Karachi (Chapter-2)', 'Karachi', 'Campus Team', 'https://chat.whatsapp.com/BHsVXUC0SZY0I1VlQfcS5p', 81, 'Official'),
('Bahauddin Zakariya University', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/D7ohR5PuzBeCb55sBylSh6', 88, 'Growing'),
('University of the people', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/KzlMCIzw6mxDHJhw9PI1dA', 95, 'Top Active'),
('UIT Chapter', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/DQUE3tNGSz6J7ToZvLA9sB', 102, 'Growing'),
('IQ School of Finance, Karachi for CA', 'Karachi', 'Campus Team', 'https://chat.whatsapp.com/LaSBbZFdLQC6cqwM4Phyzi', 29, 'Official'),
('GUTECH', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/H7BGVLdV6gaHlu9KHdofln', 36, 'Growing'),
('Muhammad Nawaz Shareef University of Agriculture', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/LWLU9vBDCN96hk26DAYtuP', 43, 'Official'),
('UMT Lahore', 'Lahore', 'Campus Team', 'https://chat.whatsapp.com/EuiWqgtR0iDLPyXKCFDnTC', 50, 'Top Active'),
('UET Chap 2', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/HN1wteTbbJP9Aw8gYPqxS0', 57, 'Official'),
('NED Chapter-5', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/KwFqr6K2puQLRIuGDHLtGT', 64, 'Growing'),
('Govt. College University – Faisalabad', 'Faisalabad', 'Campus Team', 'https://chat.whatsapp.com/FsV6GZ2LhBr7JogE2S4von', 71, 'Official'),
('University of Sufism and Modern Sciences', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/G22stL5TFDq3XlE1k8K1HU', 78, 'Growing'),
('(NUST) – Islamabad Chapter', 'Islamabad', 'Campus Team', 'https://chat.whatsapp.com/FE9ktleYChSFy2AT7pw2St', 85, 'Top Active'),
('UMT Sialkot', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/JTRwE1Qm4R6980P7quMZ28', 92, 'Growing'),
('COMSATS University Chapter 01', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/IyychsiCZixAQLzmyCHNIj', 99, 'Official'),
('Comsat Lahore Chap', 'Lahore', 'Campus Team', 'https://chat.whatsapp.com/CwmqjdTFKoYK2aB9zA6ar3', 26, 'Growing'),
('Government Graduate College for Women ,Bahawalpur Chap', 'Bahawalpur', 'Campus Team', 'https://chat.whatsapp.com/C1im36NFF5fApRUH4BiwOH', 33, 'Official'),
('College for Women University Lahore', 'Lahore', 'Campus Team', 'https://chat.whatsapp.com/IxiyQrEfjGW9ZAvxP52mvO', 40, 'Top Active'),
('Dawood University Chapter 01', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/HtVfPxaatE9CqbdcTPEwHA?s=cl&p=a&mlu=4&ilr=4', 47, 'Official'),
('JMDC Chapter', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/BtybFVKO7Xw9lqCA1ExO19', 54, 'Growing'),
('Dawood University Chapter 03', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/IBWgKcmEKcn4SU4IwuAlS0', 61, 'Official'),
('Allama Iqbal Open University', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/C4UjwaOrhdw8mPgLi0AZKL', 68, 'Growing'),
('FJWU Chapter 1', 'Rawalpindi', 'Campus Team', 'https://chat.whatsapp.com/CsbERpraxHeEpFsLq2zGLJ?s=cl&p=a&mlu=4&ilr=4', 75, 'Top Active'),
('Green international university lahore', 'Lahore', 'Campus Team', 'https://chat.whatsapp.com/Kscp8lbffnO82c6qtTuCjX?s=cl&p=a&mlu=4&ilr=4', 82, 'Growing'),
('Dawood University Chapter 04', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/EKsArpAXMM06wxXMoCinJS?s=cl&p=a&mlu=4&ilr=4', 89, 'Official'),
('JMDC Chapter', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/BtybFVKO7Xw9lqCA1ExO19?s=cl&p=a&mlu=4&ilr=4', 96, 'Growing'),
('Comsat Lahore Chap', 'Lahore', 'Campus Team', 'https://chat.whatsapp.com/CwmqjdTFKoYK2aB9zA6ar3?s=cl&p=a&mlu=4&ilr=4', 103, 'Official'),
('Government Graduate College for Women ,Bahawalpur Chap', 'Bahawalpur', 'Campus Team', 'https://chat.whatsapp.com/C1im36NFF5fApRUH4BiwOH?s=cl&p=a&mlu=4&ilr=4', 30, 'Top Active'),
('GUTECH Chapter', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/H7BGVLdV6gaHlu9KHdofln?s=cl&p=a&mlu=4&ilr=4', 37, 'Official'),
('Ziauddin University', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/F3hfgr7OVHp7E3aIKctjCC?s=cl&p=a&mlu=4&ilr=4', 44, 'Growing'),
('SZABIST  Hyderabad', 'Sindh / Jamshoro', 'Campus Team', 'https://chat.whatsapp.com/FxATs4PpoAU6lQghYXxQhu?s=cl&p=a&mlu=4&ilr=4', 51, 'Official'),
('University of Swabi', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/IerAgoEAedz3rfHO4pr1ra?s=cl&p=a&mlu=4&ilr=4', 58, 'Growing'),
('Bahria University Chapter 03', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/FVBVTOiBRR9GesApzL9rjf?s=cl&p=a&mlu=4&ilr=4', 65, 'Top Active'),
('Govt islamia law college Karachi', 'Karachi', 'Campus Team', 'https://chat.whatsapp.com/KMYq2Bo3tjs6dcuaaff7XF?s=cl&p=a&mlu=4&ilr=4', 72, 'Growing'),
('Pakistan Institute of Engineering & Applied Sciences (PIEAS) - Chapter 2', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/EKctxR8J21XK3mPmEGCp74?s=cl&p=a&mlu=4&ilr=4', 79, 'Official'),
('Shaheed Benazir Bhutto University', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/BfQZ3lcNwpDCPy4I0wEt1M?s=cl&p=a&mlu=4&ilr=4', 86, 'Growing'),
('DHA suffa Chapter 02', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/KvUvH8OboLY58LKPUJNOTl?s=cl&p=a&mlu=4&ilr=4', 93, 'Official'),
('National University of Pakistan', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/Ii68XINSWnnCm3f8uQqUME?s=cl&p=a&mlu=4&ilr=4', 100, 'Top Active'),
('Allama Iqbal Open University', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/C4UjwaOrhdw8mPgLi0AZKL?s=cl&p=a&mlu=4&ilr=4', 27, 'Official'),
('NED Chapter-7', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/HsuEBniMOCFB3YEmnRCX8M?s=cl&p=a&mlu=4&ilr=4', 34, 'Growing'),
('University of the people', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/KzlMCIzw6mxDHJhw9PI1dA?s=cl&p=a&mlu=4&ilr=4', 41, 'Official'),
('Quaid-e-Awam University', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/INpXL56gWjVDF3C64MvKPX?s=cl&p=a&mlu=4&ilr=4', 48, 'Growing'),
('Punjab University College of Information Technology', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/EXODcEQkkiMIi3tt4tC0Mh?s=cl&p=a&mlu=4&ilr=4', 55, 'Top Active'),
('Himayat e islam degree College for women', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/Dsb0UCI6LhcBOyHAvGDhUh?s=cl&p=a&mlu=4&ilr=4', 62, 'Growing'),
('SZABIST LARKANA', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/HYU6u2qhYeN1eG5yPPzTlw?s=cl&p=a&mlu=4&ilr=4', 69, 'Official'),
('CV • Linkedin – Information Technology University', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/E1nMBWpQm1o5SVhLq5Lz5t?s=cl&p=a&mlu=4&ilr=4', 76, 'Growing'),
('CV • Linkedin – National University of Pakistan', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/LRHH6zMC6SjELJA4YFuFTP?s=cl&p=a&mlu=4&ilr=4', 83, 'Official'),
('Lasbela University of Agriculture, Water and Marine Sciences', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/FBtVZMg6SI09wXPqbOBKkW?s=cl&p=a&mlu=4&ilr=4', 90, 'Top Active'),
('Qarshi University', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/HEapBqjfDziLQjBKerBJ7N?s=cl&p=a&mlu=4&ilr=4', 97, 'Official'),
('University of Agriculture (UAF) (Faisalabad)', 'Faisalabad', 'Campus Team', 'https://chat.whatsapp.com/Ih3R9aR44QCCj0w5bltfTo?s=cl&p=a&mlu=4&ilr=4', 104, 'Growing'),
('The Women University (Multan)', 'Multan', 'Masooma Fatima', 'https://chat.whatsapp.com/DXrBY9vErxw62B9vdMINOR?s=cl&p=a&mlu=4&ilr=4', 31, 'Official'),
('University of Okara', 'Pakistan', 'saiba Fatima', 'https://chat.whatsapp.com/L0r2ZIDqBIDBpI1ZDo73Ea?s=cl&p=a&mlu=4&ilr=4', 38, 'Growing'),
('Sir Syed University of Engineering and Technology (SSUET)', 'Pakistan', 'Aafia Uzair', 'https://chat.whatsapp.com/FOrX69jYVd04rVS4S4jWbw?s=cl&p=a&mlu=4&ilr=4', 45, 'Top Active'),
('Kohat University of Science and Technology (KUST)', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/ESl2pcOQUKJKyZh1UyduE9?s=cl&p=a&mlu=4&ilr=4', 52, 'Growing'),
('Riphah International University', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/F92mEsMRoOOFS5oTjRFv2M?s=cl&p=a&mlu=4&ilr=4', 59, 'Official'),
('Salim Habib University (SHU)', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/Drk9zNo2QHZHZcp8M7fOsW?s=cl&p=a&mlu=4&ilr=4', 66, 'Growing'),
('Baltistan University', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/DzouwoG9bfp5N3WzRVEGWU?s=cl&p=a&mlu=4&ilr=4', 73, 'Official'),
('Hamdard University', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/JJDNEowMWjNHL1sUkXk7PF?s=cl&p=a&mlu=4&ilr=4', 80, 'Top Active'),
('University of Gujrat', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/KicxSkWyVFBFeLGbn6ZRbf?s=cl&p=a&mlu=4&ilr=4', 87, 'Official'),
('CV • Linkedin – Khwaja Fareed University of Engineering & Information Technology', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/DsFwDeBpJGHG7NiMLc6GbS?s=cl&p=a&mlu=4&ilr=4', 94, 'Growing'),
('CV • Linkedin — Karakoram International University', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/IOoejUj2Nig6f4gLlRdpg5?s=cl&p=a&mlu=4&ilr=4', 101, 'Official'),
('CV • Linkedin — Al kahf institute', 'Pakistan', 'Campus Team', 'https://chat.whatsapp.com/IRjldbjChHOAnpvSFlGkTB?s=cl&p=a&mlu=4&ilr=4', 28, 'Growing');

INSERT INTO ambassadors (name, email, phone, university, chapter_name, status) VALUES
('syed wasif', 'syedwasif@cortexa.ai', '+92 300 0000000', '(Dawood University ) Chapter', '(Dawood University ) Chapter', 'Active'),
('Khadija Malik', 'khadijamalik@cortexa.ai', '+92 300 0000000', 'FJWU Chapter 1', 'FJWU Chapter 1', 'Active'),
('Bushra Ashraf Bhatti', 'bushraashrafbhatti@cortexa.ai', '+92 300 0000000', 'FJWU Chapter 1', 'FJWU Chapter 1', 'Active'),
('Hafsa Noor', 'hafsanoor@cortexa.ai', '+92 300 0000000', 'IBA Sukkur Chapter 02', 'IBA Sukkur Chapter 02', 'Active'),
('Sanjana Lokwani', 'sanjanalokwani@cortexa.ai', '+92 300 0000000', 'SZABIST Karachi Chapter 01', 'SZABIST Karachi Chapter 01', 'Active'),
('Aiman Iqbal', 'aimaniqbal@cortexa.ai', '+92 300 0000000', 'FJWU Chapter 4', 'FJWU Chapter 4', 'Active'),
('Rabya Samman', 'rabyasamman@cortexa.ai', '+92 300 0000000', 'University of the Punjab Chapter', 'University of the Punjab Chapter', 'Active'),
('Abdul Waris', 'abdulwaris@cortexa.ai', '+92 300 0000000', 'Dawood University Chapter 02', 'Dawood University Chapter 02', 'Active'),
('Daniyal Ismail', 'daniyalismail@cortexa.ai', '+92 300 0000000', 'Dawood University Chapter 02', 'Dawood University Chapter 02', 'Active'),
('Manahil Rehman', 'manahilrehman@cortexa.ai', '+92 300 0000000', 'University of Mianwali Chap 2', 'University of Mianwali Chap 2', 'Active'),
('Manahil Rehman', 'manahilrehman@cortexa.ai', '+92 300 0000000', 'University of Mianwali', 'University of Mianwali', 'Active'),
('Shazia Bibi', 'shaziabibi@cortexa.ai', '+92 300 0000000', 'University of Mianwali', 'University of Mianwali', 'Active'),
('Tanzila Younas', 'tanzilayounas@cortexa.ai', '+92 300 0000000', 'Namal University Chapter', 'Namal University Chapter', 'Active'),
('Taha fayyaz', 'tahafayyaz@cortexa.ai', '+92 300 0000000', 'Bahria University Chapter 02', 'Bahria University Chapter 02', 'Active'),
('Tanzila Anwar', 'tanzilaanwar@cortexa.ai', '+92 300 0000000', '(Government College University)', '(Government College University)', 'Active'),
('Agha Hassan Mavia', 'aghahassanmavia@cortexa.ai', '+92 300 0000000', 'MAJU Chapter', 'MAJU Chapter', 'Active'),
('Timsal Hassan', 'timsalhassan@cortexa.ai', '+92 300 0000000', 'The Islamia University of Bahawalpur', 'The Islamia University of Bahawalpur', 'Active'),
('Masooma Fatima', 'masoomafatima@cortexa.ai', '+92 300 0000000', 'The Women University (Multan)', 'The Women University (Multan)', 'Active'),
('Saiba Fatima', 'saibafatima@cortexa.ai', '+92 300 0000000', 'The Women University (Multan)', 'The Women University (Multan)', 'Active'),
('saiba Fatima', 'saibafatima@cortexa.ai', '+92 300 0000000', 'University of Okara', 'University of Okara', 'Active'),
('Masooma Fatima', 'masoomafatima@cortexa.ai', '+92 300 0000000', 'University of Okara', 'University of Okara', 'Active'),
('Aafia Uzair', 'aafiauzair@cortexa.ai', '+92 300 0000000', 'Sir Syed University of Engineering and Technology (SSUET)', 'Sir Syed University of Engineering and Technology (SSUET)', 'Active'),
('M.Hassan Asif', 'mhassanasif@cortexa.ai', '+92 300 0000000', 'Sir Syed University of Engineering and Technology (SSUET)', 'Sir Syed University of Engineering and Technology (SSUET)', 'Active'),
('Maliha Siddique Khan', 'malihasiddiquekhan@cortexa.ai', '+92 300 0000000', 'Sir Syed University of Engineering and Technology (SSUET)', 'Sir Syed University of Engineering and Technology (SSUET)', 'Active'),
('Muhammad Arsalan Zahid', 'muhammadarsalanzahid@cortexa.ai', '+92 300 0000000', 'Sir Syed University of Engineering and Technology (SSUET)', 'Sir Syed University of Engineering and Technology (SSUET)', 'Active'),
('Zaid Khan', 'zaidkhan@cortexa.ai', '+92 300 0000000', 'Sir Syed University of Engineering and Technology (SSUET)', 'Sir Syed University of Engineering and Technology (SSUET)', 'Active'),
('Sabih Ahmed', 'sabihahmed@cortexa.ai', '+92 300 0000000', 'Sir Syed University of Engineering and Technology (SSUET)', 'Sir Syed University of Engineering and Technology (SSUET)', 'Active'),
('Huzaifa Bin Sabeeh khadija kubra', 'huzaifabinsabeehkhadijakubra@cortexa.ai', '+92 300 0000000', 'Sir Syed University of Engineering and Technology (SSUET)', 'Sir Syed University of Engineering and Technology (SSUET)', 'Active'),
('zoya zia', 'zoyazia@cortexa.ai', '+92 300 0000000', 'Sir Syed University of Engineering and Technology (SSUET)', 'Sir Syed University of Engineering and Technology (SSUET)', 'Active');
